name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu primeiro job"
    runs-on: ubuntu-22.04
    steps:
      - name: "Minha primeira acçao"
        run: echo "Ola mundo!"
      - name: "Segunda ação"
        run: |
          echo "Você criou o seu primeiro workflow !!!
